---
title: "Summary of the NWFSC West Coast groundfish survey data for select species from 2003-2019"
author: ''
date: ''
output:
  pdf_document:
    fig_caption: yes
    highlight: haddock
    includes:
      before_body: Titlepage.tex
      in_header: header.tex
    keep_tex: yes
    number_sections: yes
    template: Default_template_modified.tex
    toc: yes
    toc_depth: 4
  html_document:
    toc: yes
  word_document:
    toc: yes
    toc_depth: '4'
documentclass: article
fontsize: 12pt
geometry: margin=1in
link-citations: yes
#csl: CJFAS.csl
#bibliography: Bib_July09.bib
#output:
#  uswebr::html_uswds
#documentclass: book
#fontsize: 11pt
#output:
#  pdf_document:   
#    keep_tex: yes
#header-includes:
#   - \RequirePackage{accsupp}
#   - \RequirePackage{pdfcomment}
#   - \newcommand{\AccTool}[2]{\BeginAccSupp{method=pdfstringdef,unicode,Alt={{#1}}}\pdftooltip{{#2}}{{#1}}\EndAccSupp{}}
---


```{r global_options, include=FALSE}

    knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.pos ='!ht')
```


```{r, results='asis'}
  options(stringsAsFactors = FALSE)
  library(HandyCode)
  library(xtable)
  library(knitr)
  library(kableExtra)
  dir = "C:/Assessments/2020/survey_summary/survey_summary_package/doc"
  source(paste0(dir, "/code/legend_code.R"))
  
  # Figure sizing
  index_size = "60%"
  comp_size  = "60%"
  sum_size   = "60%"
  depth_size = "60%"

```

\setlength{\parskip}{5mm plus1mm minus1mm}
\pagebreak


\setcounter{page}{1}


\pagenumbering{arabic}


```{r child = "1_intro.Rmd"}
```


```{r child = "2_plots.Rmd"}
```



