# Introduction 

This document provides a detailed summary of commonly used data sources that may be used to support assessments in `r assess_year`. A detailed summary of data available by year and across sources can allow the Pacific Fishery Management Council (Council) and advisory bodies to understand the coverage of data across time and the potential viability of a new assessment or assessment type. The following additions and changes have been done relative the the version of this report provided at the March 2024 Council meeting:

* Relative indices of abundance for species observed by the Northwest Fisheries Science Center (NWFSC) West Coast Groundfish Bottom Trawl (WCGBT) survey have been added.

* Relative indices of abundance for species observed by the NWFSC Hook-and-Line (HKL) survey have been added. Summaries of data collected between 2004-2023 are now included.

* Relative juvenile indices of abundance for selected species that are well observed at small sizes by the NWFSC WCGBT survey have been added. The species included are arrowtooth flounder, darkblotched rockfish, Dover sole, English sole, longspine thornyhead, Pacific sanddab, petrale sole, sablefish, shortspine thornyhead, and splitnose rockfish.

* Survey length data composition plots were included only for species identified for potential assessment in 2025 at the March Council meeting. These figures were provided in March for all species and can be found online in [Agenda Item F.3, Supplemental Attachment 4, March 2024](https://www.pcouncil.org/documents/2024/02/agenda-item-f-3-supplemental-attachment-4-summary-of-available-data-to-support-u-s-west-coast-groundfish-stock-assessments.pdf/).

* A preliminary relative index of abudance from the International Pacific Halibut Commission (IPHC) survey is included for yelloweye rockfish based on sample stations off the Washington coast. The preliminary index was estimated by staff at Washington Department of Fish and Wildlife (WDFW). A future assessment of yelloweye rockfish may further refine how these data are modeled potentially resulting in slight changes in the year-to-year estimates. A plot of the designed-based (raw catch-per-unit-effort) estimates is included for comparison. 

* A three-panel figure visualizing California quillback rockfish age and length from read age structures by the Cooperative Ageing Program (CAP) lab to date (4/11/2024), the distribution of lengths from read and unread age structures by data source at the CAP ageing lab, and the distribution of ages from read age structures.

## Biological Samples

Data from Pacific Fisheries Information Network (PacFIN), Recreational Fisheries Information Network (RecFIN), Southwest Fisheries Science Center (SWFSC) Commercial Passenger Fishing Vessel (CPFV) cooperative collections, California Collaborative Research Program (CCFRP) survey, the Northwest Fisheries Science Center (NWFSC) West Coast Groundfish Bottom Trawl Survey (WCGBT), and NWFSC Hook-and-Line (HKL) surveys are summarized. 

Commercial data summaries were downloaded from PacFIN on December 13, 2023. The number of length samples, aged fish, and unread age structures (e.g., otoliths, fin rays, or spines) samples by species, state, and year were summarized. Age structure records were provided directly from the WDFW for `r startyr`-`r endyr` and Pacific States Marine Fisheries Council (PSMFC) commercial collection in California for 2011-`r endyr`. Oregon Department of Fish and Wildlife (ODFW) confirmed that age structure records in PacFIN were correct and recommended using these data directly. Data available between `r startyr`-`r endyr` are summarized here.

Recreational data summaries were downloaded from RecFIN on December 13, 2023. The number of length samples, aged fish, and unread age structures were summarized by species and state between `r startyr`-`r endyr`. Available age and age structure counts for Oregon and Washington were downloaded from RecFIN on January 30, 2024. 

Data collected by the NWFSC WCGBT survey between 2003-`r endyr` and the NWFSC HKL survey from 2004-`r endyr` are summarized by species. Similar to the summaries provided for the commercial and recreational fisheries; lengths, aged fish, and unread age structures collected are available by year. Additionally, the number of tows (NWFSC WCGBT survey) or sites (NWFSC HKL survey) that observed each species by year are also provided. CCFRP length samples by year and species are summarized here as well. No additional CCFRP data are included in this report. A separate report detailing CCFRP data is available in the March Briefing Book under [Agenda Item F.3, Attachment 3, March 2024](https://www.pcouncil.org/documents/2024/02/agenda-item-f-3-attach-3-california-collaborative-fisheries-research-program-data-availability-for-stock-assessments.pdf/). 

## California Ad-hoc Age-Structure Collections

California Department of Fish and Wildlife (CDFW) provided age structure sample numbers collected via various methods from commercial and recreational fisheries. These samples were collected outside the standard sampling protocol for either California Recreational Fisheries Survey (CRFS) or the Pacific States Marine Fisheries Commission (PSMFC) commercial sampling program. These collections were labeled as "CDFW Ad-hoc" collections for each species. Details on the collection methodology for the recreational and commercial samples are below. 

There are no age or age structure sample data in RecFIN that have been collected from California recreational fisheries. Recent age structure collections from 2017-`r endyr` were provided directly by CDFW. The recreational age structure collections provided by CDFW were collected by various methods: 1) from angler surrendered fish for copper rockfish, quillback rockfish, and yelloweye rockfish that were kept in excess of recreational bag limits or were prohibited to be retained, 2) cowcod under CDFW's Exempted Fishing Permit encountered incidentally by Commercial Passenger Fishing Vessels, and 3) randomly sampled species from private/rental and party/charter recreational vessels. Any future assessment, will need to investigate the California recreational age structures for representativeness to determine whether they could be linked to a recreational fleet within a model.

Age structures collected from 12 groundfish species in 2019 by CDFW from purposive sampling (i.e., non-random) from commercially landed fish. This commercial pilot project involved obtaining randomly selected fish from participating fish businesses, either at the time of landing, or in the case of multiple landings utilizing the same gear type, after the landing had occurred. These ages would not be associated with a commercial fleet in an assessment due to their non-random collections.

Age structures collected from carcasses of groundfish species between 2017-2019 by CDFW recreational fisheries. These collections may be considered by future assessments but would likely only be used as marginal ages (i.e., would not inform growth) given the uncertainty around the true fish length (e.g., length prior to filleting).

## Survey Length Compositions

The length data collected by the NWFSC WCGBT survey were expanded using a generalized area-based stratification. The composition data were expanded using a design-based approach with strata based on state latitudes with two depth strata: 55 - 183 m and 183 - 549 m, with an exception for four specie. The four species have considerable biomass at depths greater than 549 m: sablefish, Dover sole, longspine thornyhead, and shortspine thornyhead. Thus an additional depth strata that covered deeper waters, 549 - 1,280 m, for each state area was added. The expanded length composition data were summarized using either a 2 or 4 cm bin structure depending upon the range between maximum and minimum lengths observed within the survey data.  Species where the range between the maximum and minimum lengths observed by the survey were less than 60 cm, 2 cm data bins were used, while for species where the range was 60 cm or greater the data bins were set at 4 cm. All length observations were treated as unsexed fish in this exercise for simplicity and for ease of observing potential trends in length observations across time. The generalized stratification and bin structure selected here provides a simple summary of the data that can be useful for decision making, but will likely differ from a species-specific approach that would be selected in a future assessment. Additionally, the NWFSC WCGBT survey selectivity for each species will impact the lengths observed and has not been explicitly accounted for in this analysis.

The length data collected by the NWFSC HKL survey were summarized to reflect the proportion of observations by species, length bin, and year. The length composition data were summarized using either a 2 or 4 cm bin structure depending upon the range between maximum and minimum lengths observed within the survey data, in the same manner as for the NWFSC WCGBT survey. Similar to the NWFSC WCGBT survey, the selectivity of the NWFSC HKL survey for each species will impact the lengths observed and has not been explicitly accounted for in this analysis.

The length data plots for the CCFRP survey are not provided here. For detailed information about CCFRP survey data please see the separate [CCFRP report](https://www.pcouncil.org/documents/2024/02/agenda-item-f-3-attach-3-california-collaborative-fisheries-research-program-data-availability-for-stock-assessments.pdf/).

## Survey Relative Indices of Abundance

Indices of abundance were estimated from the NWFSC WCGBT survey using a spatiotemporal model (smdTMB) for species well-observed by the survey. The indices were estimated using a generalized set-up across species using either a gamma or log-normal distribution, with the dispersion parameter held constant across years with 200-500 knots used to create the mesh. The model structure for each species is provided in Section \ref{wcgbt-index-settings}. Future species-specific indices of abundance created with sdmTMB would likely select a more tailored approach for model settings (e.g., knots, distributions) which could result in slight changes in year-by-year values for the indices of abundance. The indices of abundance presented here should only be considered illustrative of potential trends in abundance across time. 

Indices of abundance were estimated from the NWFSC HKL survey for well-observed species using a negative-binomial model that accounted for year, site, and drop number. Additional covariates that would typically be explored when developing species-specific indices for use in stock assessments were not explored in this analysis for simplicity. The selection of how to model these data for a particular species may vary from the approach applied here. For example, the recent vermilion and sunset rockfish assessment modeled the data as two indices (i.e., one for areas outside of the Cowcod Conservation Areas [CCA] and one for sites inside the CCAs). In contrast, the recent assessment of copper rockfish estimated a single index with observations by areas weighted (nearshore sites, northern Channel Islands, Southern Channel Islands). 

## Maturity Data Collections

Maturity samples for a wide range of West Coast groundfish species have been collected across a range of sources: NWFSC WCGBT survey, NWFSC HKL survey, Pacific hake survey, at-sea sampling of the Pacific hake fishery, and port sampling by ODFW and WDFW. Samples have been collected between 2009 - 2022. The following summary does not include collection from the 2023 NWFSC WCGBT and HKL surveys. Summaries of the maturity collections is provided for each species. This data summary only includes collections led by the NWFSC but other collections could be available at the SWFSC, CDFW, ODFW, WDFW, or other research groups. Future data summaries will look to integrate these additional collections in subsequent versions of this document.     

## Additional Data

Data may be available for consideration in future assessments that are currently not included in this report. A summary of potential additional data that could be available are described below:

* Totals for data collected in 2023 in PacFIN and RecFIN are incomplete for all states.

* Data collected in 2023 by the CCFRP are not yet available. Additionally, in recent years CCFRP has been collecting age structures from a small number of fish from the reference area (i.e., areas open to fishing). The numbers of age structures and aged fish from this survey were not available for this report. There is a separate document is provided that summarizes data collected by the CCFRP for select species that details the number of samples by location, area type (marine protected area or reference area), and plots of available length compositions. 

* Historical data collections from various research projects exist at the SWFSC that have not been cataloged and entered into any database. Species-specific searches may yield additional samples within these collections.

While this document only summarizes data from 2000-2023, there are additional data available from earlier years that could be incorporated into future assessments.

* ODFW and WDFW have substantial collections from periods prior to the years summarized in this report from their commercial and recreational sampling programs.

* CDFW is undergoing a review of historical age structures collections (i.e., referred to as refugia samples) for samples from the 1980s and earlier. If sufficient documentation exists for these historical samples they could be potentially included in future assessments. Since this work is ongoing it is unclear how many samples may be available across species.  

Finally, summarizing commercial and recreational data from each state accurately continues to be challenging due to differences by state in what information is transmitted to PacFIN and RecFIN (e.g., California commercial age structure collections). Receiving and understanding the available commercial and recreational data requires emailing various representative in each state who thankfully have been accommodating in answering questions and providing additional data summaries. However, given the challenges around acquiring and collating, data summaries may not be comprehensive or have unintentional errors. Any issues identified will be addressed in future versions.

\newpage


