
# Preface
This document is an update the initial summary provided for the March 2020 Pacific Fishery Management Council meeting.  The changes between this document an the one provided in March are as follows:

\begin{enumerate}

\item The NWFSC West Coast Groundfish Bottom Trawl Survey (WCGBTS) data from 2019 are now available and have been added to the summaries;
\item Summaries for the following species have been added: petrale sole, sablefish, big skate, longnose skate, widow rockfish, and Pacific ocean perch;
\item The index of abundance for select species was calculated splitting area-based estimates by South and North of the N. 40$^\circ$ 10' latitude ( splitnose rockfish and yellowtail rockfish);
\item The index of abundance for sablefish was calculated splitting are based estimates by Sount and North of the N. 36$^\circ$ latitude; and,
\item The March version had incorrect labeling of the estimated indices of abundance for the following species: yellowtail rockfish, splitnose rockfish, and shortspine thornyhead.  This has been corrected.

\end{enumerate}

# Introduction
A brief summary of the NWFSC West Coast Groundfish Bottom Trawl Survey (WCGBTS) is presented here for data available from 2003 - 2019.  These analyses are meant to provide additional information and guidance for the 2020 assessment prioritization process.  The selection of the species was based on having an average of 20 or more positive tows by the survey per year.  

The indices were calculated using VAST and the biomass estimates were aggregated by a generalized approach using state boundaries based on the areas where observations were present. Future species specific assessments may select a more tailored approach for summarizing the NWFSC WCGBTS data by area.  

The length data also were expanded using a generalized stratification. The composition data were expanded using a design-based approach with stratas based on state latitudes with two depth stratas: 55 - 183 m and 183 - 549 m, for all species except for three.  The three exceptions were species with considerable biomass at depths greater than 549 m: Dover sole, longspine thornyhead, and shortspine thornyhead.  These three species had an additional depth strata that included deeper waters, 549 - 1280 m, for each state area. The expanded length composition data were summarized using either a 2 or 4 cm bin structure depending upon the range between maximum and minimum lengths observed within the survey data.  Species where the range between the maximum and minimum lengths observed by the survey were less than 60 cm, 2 cm data bins were used, and for species where the range was 60 cm or greater the data bins were set at 4 cm.  The generalized stratification and bin structure selected here provides a simple summary of the data that can be useful for decision making, but will likely differ from a species specific approach that would be selected in a future assessment.  

\newpage
