
## Arrowtooth flounder test
```{r echo = FALSE, results = "asis", fig.cap= "figure caption"}

i = 1
name = gsub("_", " ", firstup(all[i]))
if(!is.na(sum.lab[i,3])){ 
# trawl survey data first
cat('\n![',sum.lab[i,3],'\\label{fig:nwfsc_',sum.lab[i,1],'_sum}](C:/Assessments/2020/survey_summary/sum_plots/',sum.lab[i,1],'_survey_stats.png){width=',comp_size,'}\n',sep='')
}

```


```{r echo = FALSE, results = "asis", fig.cap= sum.lab[,3]}

input <- data.frame(
  name = all,
  stringsAsFactors = FALSE)

 template <- "##  %s

" # dont't forget the newline
 
 float <- "\\FloatBarrier  

" # dont't forget the newline
 
 new <- "\\newpage  

" # dont't forget the newline

for (i in 1:length(all)) {
  
name = gsub("_", " ", firstup(all[i]))

if(!is.na(sum.lab[i,3])){ 
# trawl survey data first
cat('\n![',sum.lab[i,3],'\\label{fig:nwfsc_',sum.lab[i,1],'_sum}](C:/Assessments/2020/survey_summary/sum_plots/',sum.lab[i,1],'_survey_stats.png){width=',comp_size,'}\n',sep='')}
  
cat(float)
  
}

```



```{r echo = FALSE, results = "asis", fig.cap= sum.lab[,3]}

input <- data.frame(
  name = all,
  stringsAsFactors = FALSE)

 template <- "##  %s

" # dont't forget the newline
 
 float <- "\\FloatBarrier  

" # dont't forget the newline
 
 new <- "\\newpage  

" # dont't forget the newline

for (i in 1:length(all)) {
  name = gsub("_", " ", firstup(all[i]))
  
  cat(sprintf(template, name))
 
  if(!is.na(sum.lab[i,3])){ 
    # trawl survey data first
    cat('\n![',sum.lab[i,3],'\\label{fig:nwfsc_',sum.lab[i,1],'_sum}](C:/Assessments/2020/survey_summary/sum_plots/',sum.lab[i,1],'_survey_stats.png){width=',comp_size,'}\n',sep='')
  }
  
 
  cat(float)
  #if (i %in% seq(3, length(species), 3) ) { cat(new) }
  
}

```
