#' List of species names to pull from NWFSC survey data
#' 
#' @author Chantel Wetzel
#' @export
#'
get_species_list <- function(){
#default <- getOption('warn')
#options(warn = -1)

species <- rbind(
	c("sablefish",  "sablefish"),
	c("longnose skate",  "longnose skate"),
	c("gopher rockfish", "gopher and black and yellow rockfish"),
	c("black and yellow rockfish", "gopher and black and yellow rockfish"),
	c("black-and-yellow rockfish", "gopher and black and yellow rockfish"),
	c("gopher/black and yellow rockfish", "gopher and black and yellow rockfish"),
	c("cabezon", "cabezon"),
	c("cowcod", "cowcod"),
	c("black rockfish",   "black rockfish"),
	c("Pacific cod", "Pacific cod"),
	c("pacific cod", "Pacific cod"),
	c("brown rockfish", "brown rockfish"),
	c("copper rockfish", "copper rockfish"),
	c("petrale sole", "petrale sole"),
	c("Dover sole", "Dover sole"),
	c("dover sole", "Dover sole"),
	c("big skate", "big skate"),
	c("bank rockfish", "bank rockfish"),
	c("quillback rockfish", "quillback rockfish"),
	c("treefish", "treefish"),
	c("tree rockfish", "treefish"),
	c("shortraker rockfish", "shortraker rockfish"),
	c("grass rockfish", "grass rockfish"),
	c("Pacific sanddab", "Pacific sanddab"),
	c("pacific sanddab", "Pacific sanddab"),
	c("yelloweye rockfish", "yelloweye rockfish"),
	c("lingcod", "lingcod"),
	c("redbanded rockfish", "redbanded rockfish"),
	c("canary rockfish", "canary rockfish"),
	c("yellowtail rockfish", "yellowtail rockfish"),
	c("yellowtail rockfish north", "yellowtail rockfish north"),
	c("yellowtail rockfish south", "yellowtail rockfish south"),
	c("squarespot rockfish", "squarespot rockfish"),
	c("splitnose rockfish", "splitnose rockfish"),
	c("widow rockfish", "widow rockfish"),
	c("speckled rockfish", "speckled rockfish"),
	c("Pacific spiny dogfish", "Pacific spiny dogfish"),
	c("pacific spiny dogfish", "Pacific spiny dogfish"),
	c("spiny dogfish", "Pacific spiny dogfish"),
	c("dogfish shark", "Pacific spiny dogfish"),
	c("sand sole", "sand sole"),
	c("olive rockfish", "olive rockfish"),
	c("shortspine thornyhead", "shortspine thornyhead"),
	c("kelp rockfish", "kelp rockfish"),
	c("starry rockfish", "starry rockfish"),
	c("rex sole", "rex sole"),
	c("flathead sole", "flathead sole"),
	c("starry flounder", "starry flounder"),
	c("greenstriped rockfish", "greenstriped rockfish"),
	c("English sole", "English sole"),
	c("english sole", "English sole"),
	c("rougheye rockfish", "rougheye and blackspotted rockfish"),
	c("blackspotted rockfish", "rougheye and blackspotted rockfish"),
	c("rougheye/blackspotted rockfish", "rougheye and blackspotted rockfish"),
	c("rougheye and blackspotted rockfish", "rougheye and blackspotted rockfish"),
	c("flag rockfish",  "flag rockfish"),
	c("China rockfish",  "China rockfish"),
	c("china rockfish",  "China rockfish"),
	c("chilipepper", "chilipepper"),
	c("chilipepper rockfish",  "chilipepper"),
	c("bocaccio",  "bocaccio"),
	#c("rock sole", "rock sole"),
	#c("northern rock sole", "northern rock sole"),
	#c("southern rock sole" ,  "southern rock sole"),
	c("California scorpionfish", "California scorpionfish"),
	c("california scorpionfish", "California scorpionfish"),
	c("longspine thornyhead", "longspine thornyhead"),
	c("blue rockfish", "blue and deacon rockfish"),
	c("deacon rockfish", "blue and deacon rockfish"),
	c("blue / deacon rockfish", "blue and deacon rockfish"),
	c("blue and deacon rockfish", "blue and deacon rockfish"),
	c("arrowtooth flounder",   "arrowtooth flounder"),
	c("kelp greenling",   "kelp greenling"),
	c("greenspotted rockfish",   "greenspotted rockfish"),
	c("darkblotched rockfish",   "darkblotched rockfish"),
	c("blackgill rockfish",   "blackgill rockfish"),
	c("aurora rockfish",   "aurora rockfish"),
	c("Pacific ocean perch",   "Pacific ocean perch"),
	c("pacific ocean perch",   "Pacific ocean perch"),
	c("sharpchin rockfish",   "sharpchin rockfish"),
	c("vermilion rockfish",   "vermilion and sunset rockfish"),
	c("sunset rockfish",  "vermilion and sunset rockfish"),
	c("vermilion/sunset rockfish", "vermilion and sunset rockfish"),
	c("vermilion and sunset rockfish", "vermilion and sunset rockfish"),
	c("honeycomb rockfish", "honeycomb rockfish"),
	c("curlfin sole", "curlfin sole"),
	c("leopard shark", "leopard shark"),
	c("redstripe rockfish", "redstripe rockfish"),
	c("rosethorn rockfish", "rosethorn rockfish"),
	c("rosy rockfish", "rosy rockfish"),
	c("silvergray rockfish", "silvergray rockfish"),
	c("yellowmouth rockfish", "yellowmouth rockfish"),
	c("stripetail rockfish", "stripetail rockfish"))

colnames(species) <- c("name", "use_name")

return(species)

}
